Feat/profile screen
giotevdorashvili/Instagram-App pull request #2
Opened 2023-12-27 15:09 UTC by giotevdorashvili

Profile screen refactor

2024-01-09 06:48 UTC, alexkutaladze-ms requested changes

2024-01-09 06:48 UTC, alexkutaladze-ms commented on src/hooks/services/useUploadImage.ts
> +  const userId = FIREBASE_AUTH.currentUser?.uid;
userId შეიძლება გაიპაროს აქ და undefined იყოს. ქვემოთ if ჩეკი დაამატე და გატესტე იუზერის აიდი რომ ანდეფაინდი არ იყოს და მაგ შემთხვევაში რამე ალერტი ამოაგდე. ფაირბეიზი ეგრე ძაან იშვიათად დაგაღალატებს მაგრამ რეალურ პროექტში უნდა შეამოწმო ხოლმე ასეთი რაღაცები.

2024-01-09 06:48 UTC, alexkutaladze-ms commented on src/navigators/rootNavigator/RootNavigator.tsx
> +export const useGetNavigation = () => {
ამის აზრს ვერ მივხვდი. ჰუკს სხვა ჰუკიდან რატომ აბრუნებ?

2024-01-09 06:48 UTC, alexkutaladze-ms commented on src/navigators/rootNavigator/RootNavigatorTypes.d.ts
> +export type LogInPropTypes = ScreenProps<'LogIn'>;
ScreenProps generic ტაიპი ხომ გაქვს უკვე? ზედმეტი წვალებაა ცალკე კონკრეტული სქრინებისთვის ტაიპების დაექსპორტება. სადაც დაგჭირდება ScreenProps დააიმპორტე და მერე ჯენერიქში მიუთითე რომელი სქრინის პროპებიც გჭირდება

2024-01-09 06:48 UTC, alexkutaladze-ms commented on src/navigators/tabNavigator/TabNavigatorTyps.d.ts
> +export type HomePropTypes = ScreenProps<'Home'>;
აქაც იგივე. რახან ორივეგან ScreenProps დაარქვი ჯენერიქ ტაიპს სტეკის სქრინების ჯენერიქს StackScreen დაარქვი და ტაბებისას შესაბამისად TabScreen. უფრო ადვილადაც მიხვდები რომელი ნავიგატორის ჯენერიქია

2024-01-09 06:48 UTC, alexkutaladze-ms commented on src/services/crudUser.ts
> +    throw error;
catch-ის მთელი აზრი არის ის რომ ერორი დაიჰენდლოს იქ სადაც შენ გინდა და არ დაიქრაშოს აპლიკაცია, ანუ catch ბლოკში რო "ისვრი" ერორს ეგ anti-pattern გამოდის. ამ ფუნქციას სადაც იძახებ იქ თუ ჰენდლავ ერორს მაშინ try catch-ის გარეშე გაწერე ფუნქცია და სადაც მოგეხერხება იქ დაჰენდლე მაგის ერორი

2024-01-12 11:35 UTC, giotevdorashvili commented on src/navigators/rootNavigator/RootNavigator.tsx
> +export const useGetNavigation = () => {
`export const useRootNavigation = () => {
  return useNavigation<NativeStackNavigationProp<RootStackParamList>>();
};
`
`export const useTabNavigation = () => {
  return useNavigation<NativeStackNavigationProp<TabStackParamList>>();
};`

ესენი ცალცალკე მაქ გაკეთებული რო ტიპების გაწერა აღარ დამჭირვებოდა ყოველ ჯერზე და პირდაპირ ნავიგაცია მიმეღო

2024-01-15 14:01 UTC, merged