Feat/posts
giotevdorashvili/Instagram-App pull request #3
Opened 2024-01-08 13:57 UTC by giotevdorashvili

Created Home screen that shows account owner's posts only

2024-01-09 07:08 UTC, alexkutaladze-ms requested changes
როგორც მივხვდი ეს პოსტების ბრენჩი პროფილის ბრენჩიდან დაიწყე, იმიტორო პროფილის ბრენჩში რაზეც დაგიტოვე კომენტარები იგივე კოდი შემხვდა აქაც. შესაბამისად, აქ აღარ დაგიტოვე იგივე კომენტარები. საბოლოო ჯამში კარგი ნამუშევარია ორივე ბრენჩზე, კომენატრები რაზეც დაგიწერე ეგენი გავასწოროთ და მშვენიერი ინსტაგრამის კლონი გამოვა.

2024-01-09 07:08 UTC, alexkutaladze-ms commented on src/components/logos/InstagramWordLogo.tsx
ეს ლოგო (სიტყვაზე) სხვა ზომებში რომ დაგჭირდეს მომავალში ახლავე ჯობია height width  და svg-ს ყველა პროპი პროპებიდან აიღოს ისევ. რა  პროპების დეფოლტებიც იცი ეგ დეფოლტები გაწერე ამ კომპონენტის პროპებში

2024-01-09 07:08 UTC, alexkutaladze-ms commented on src/hooks/services/useFetchPosts.ts
პაგინაცია არ ჭირდება პოსტებს?

2024-01-09 07:08 UTC, alexkutaladze-ms commented on src/hooks/services/useUploadProfilePic.ts
> +      await updateUser(userId!, uri);
უკეთესი იქნება თუ ამ ფუნქციით იუზერის ნებისმიერ ფროფერთი(-ებ)ს დაარედაქტირებ

2024-01-09 07:08 UTC, alexkutaladze-ms commented on src/screens/tabScreens/home/Home.tsx
> +  const scrollY = useSharedValue(0);
scroll-ის ოფსეტი უფრო ადვილად შეგიძლია ნახო. დოკუმენტაციაში სქროლვიუზე არის მაგალითი აწყობილი. ნახე ფლეტლისტზეც თუ მუშაობს
https://docs.swmansion.com/react-native-reanimated/docs/scroll/useScrollViewOffset

2024-01-09 07:08 UTC, alexkutaladze-ms commented on src/screens/tabScreens/profile/profileCounter/ProfileCounter.tsx
> +      <FollowersCounter />
აქ სამივე კომპონენტი თავისუფლად შეგიძლია ერთი ზოგადი კომპონენტით ჩაანაცვლო. დაარქვი სიტყვაზე ProfileStatLabel ან რამე ეგეთი დაახლოებით, რომელსაც გადააწოდებ ორ პროპს, რაოდენობის და რაოდენობის ქვეშ დასაწერი ტექსტის (Posts, Followers, Following, etc.). სამივეს ერთი ლეიაუთი აქვს და სამივესთვის ცალკე კომპონენტის გაწერა ნამეტანი წვალებაა. მითუმეტეს, რამე რომ შეიცვალოს სტილში მოგიწევს სამივე კომპონენტში სტილის გადაწერა.

2024-01-09 07:08 UTC, alexkutaladze-ms commented on src/utils/home/utils.tsx
> +  if (seconds < 60) {
ფუნქცია სწორად არის დაწერილი მაგრამ რეალურ პროექტში ასეთ შემთხვევაში რამე date utility ფექიჯის გამოყენება ჯობია. date-fns ვიყენებ ხოლმე მე პირადად, მაგრამ შენ თუ გინდა სხვა ფექიჯი სცადე (moment, day.js) და რომელიც მოგეხერხება ის გამოიყენე. თარიღების დაფორმატებაშიც დაგეხმარება

2024-01-12 10:22 UTC, alexkutaladze-ms requested changes

2024-01-12 10:22 UTC, alexkutaladze-ms commented on src/hooks/services/useCreatePost.ts
> +  return {...mutationData, uidExists: !!userId};
ცალკე ფროფერთი არაა საჭირო, ფაირბეიზის uid-ზე წვომა ყველგან გაქვს ისედაც, სადაც დაგჭირდება იქ გაჩეკე

2024-01-12 10:22 UTC, alexkutaladze-ms commented on src/screens/rootScreens/newPost/NewPost.tsx
> +    if (!uidExists || !userId) return alertUidError();
აქ ერთი და იგივე რაღაცას ამოწმებ ორჯერ

2024-01-12 10:22 UTC, alexkutaladze-ms commented on src/components/logos/InstagramWordLogo.tsx
> +  width?: number;
SvgProps უკეთესი ტაიპია პროპებისთვის, შეიძლება სიგრძის და სიგანის გარდა სხვა რამის შეცვლაც დაგჭირდეს

2024-01-12 10:22 UTC, alexkutaladze-ms commented on src/screens/tabScreens/home/Home.tsx
> +  const scrollY = useSharedValue(0);
ეს კომენტარი გამოგრჩა

2024-01-12 11:32 UTC, giotevdorashvili commented on src/screens/tabScreens/home/Home.tsx
> +  const scrollY = useSharedValue(0);
ეს ვცადე სანდრო და არ გამოვიდა, useScrollViewOffset მარტო ScrollView_ზე მუშაობს და FlatList_ზე არ აქვთ რამე მსგავსი ჰუკი, onEndReach_ზე ტრიგერდებოდა  და არასწორ ველიუებს იღებდა

2024-01-15 14:01 UTC, merged